#ifndef __JFramework__DSP_Type_h_
#define __JFramework__DSP_Type_h_

enum DSP_Type {
  DSP_TYPE_UNKNOWN = 0,
  DSP_TYPE_MIXER,
  DSP_TYPE_OSCILLATOR,
  DSP_TYPE_LOWPASS,
  DSP_TYPE_ITLOWPASS,
  DSP_TYPE_HIGHPASS,
  DSP_TYPE_ECHO,
  DSP_TYPE_FADER,
  DSP_TYPE_FLANGE,
  DSP_TYPE_DISTORTION,
  DSP_TYPE_NORMALIZE,
  DSP_TYPE_LIMITER,
  DSP_TYPE_PARAMEQ,
  DSP_TYPE_PITCHSHIFT,
  DSP_TYPE_CHORUS,
  DSP_TYPE_VSTPLUGIN,
  DSP_TYPE_WINAMPPLUGIN,
  DSP_TYPE_ITECHO,
  DSP_TYPE_COMPRESSOR,
  DSP_TYPE_SFXREVERB,
  DSP_TYPE_LOWPASS_SIMPLE,
  DSP_TYPE_DELAY,
  DSP_TYPE_TREMOLO,
  DSP_TYPE_LADSPAPLUGIN,
  DSP_TYPE_SEND,
  DSP_TYPE_RETURN,
  DSP_TYPE_HIGHPASS_SIMPLE,
  DSP_TYPE_PAN,
  DSP_TYPE_THREE_EQ,
  DSP_TYPE_FFT,
  DSP_TYPE_LOUDNESS_METER,
  DSP_TYPE_ENVELOPEFOLLOWER,
  DSP_TYPE_CONVOLUTIONREVERB,
  DSP_TYPE_CHANNELMIX,
  DSP_TYPE_TRANSCEIVER,
  DSP_TYPE_OBJECTPAN,
  DSP_TYPE_MULTIBAND_EQ,
  DSP_TYPE_MAX
};

enum ChannelControl_DSP_Index {
  CHANNELCONTROL_DSP_HEAD = 0,
  CHANNELCONTROL_DSP_FADER,
  CHANNELCONTROL_DSP_TAIL
};

#endif
