.PHONY: clean All

All:
	@echo "----------Building project:[ JFramework - Debug ]----------"
	@$(MAKE) -f  "JFramework.mk"
clean:
	@echo "----------Cleaning project:[ JFramework - Debug ]----------"
	@$(MAKE) -f  "JFramework.mk" clean
